import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { bridge as schema } from "../bridge";
import { AutoForm } from "uniforms-mui";
import { ValidatedForm, filterDOMProps } from "uniforms";
import { useState, useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

const initModel = {
  city: "",
  state: "",
  street: "",
  zip: "",
};

export default function Home() {
  const [submitted, setSubmitted] = useState(false);
  const [formModel, setFormModel] = useState(initModel);
  const formRef = useRef();

  const handleSubmit = async (form: any) => {
    console.log({ form });
    setSubmitted(true);
    formRef.submit();
    return null;
  };

  const onValidate = async (form: any, error: any) => {
    // test just returning null, although of course
    // we would be doing some async validation here in some cases
    // and returning null sometimes to skip this async validation,
    // per Uniforms docs
    console.log("async validation");
    console.log({ error });
    return null;
  };
  console.log({ formModel });
  console.log(schema.validator(formModel));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {!submitted ? (
            <>
              <AutoForm
                onValidate={onValidate}
                schema={schema}
                model={formModel}
                validate="onChange"
                onSubmit={handleSubmit}
                ref={formRef}
              />
            </>
          ) : (
            <div>Horray! Submitted!</div>
          )}
        </div>
      </main>
    </>
  );
}
